# can also be specified as the 'ADMIN_PASSWORD' environment variable
admin_password: null

# can also be specified as the 'DATABASE_URL' or 'DB_URI' environment variable
# defaults to 'postgresql://localhost/gavel'
db_uri: null

# can also be specified as the 'SECRET_KEY' environment variable
#
# this is used to prevent tampering with sessions. this should be some
# reasonably long random string.
secret_key: null

# can also be specified as the 'PORT' environment variable
# defaults to '5000'
port: null

# can also be specified as the 'MIN_VIEWS' environment variable
# defaults to '2'
#
# this is the minimum number of times each item needs to be seen before
# switching to more sophisticated item selection strategies.
min_views: null

# can't be specified via environment variable
# defaults to gavel.constants.DEFAULT_WELCOME_MESSAGE
#
# this is the welcome message that's shown to judges before they can start
# using the system. when the message is displayed, single newlines are
# converted into spaces and text separated by two or more newlines is converted
# into separate paragraphs. it's recommended to use the YAML multiline string
# syntax when overriding this.
welcome_message: null
